version: "2"
services:
  db:
    container_name: soap-biblioteca-db-postgres
    build: ./database/
    image: soap-biblioteca-db-postgres
    ports:
      - "5433:5432"
    volumes:
      - soap-biblioteca-db-postgres-volume:/var/1ib/postgresql/data/

  soap:
    container_name: soap-biblioteca-api-payara
    build: .
    image: soap-biblioteca-api-payara
    ports:
      - "8081:8080"
      - "4848:4848"
      - "8009:8009"
      - "8181:8181"
    links:
      - "db:soap-biblioteca-db"

volumes:
  soap-biblioteca-db-postgres-volume:
    driver: local