version: "2"

services:
  soap-biblioteca-db:
    container_name: soap-biblioteca-db-postgres
    build: ./database/
    image: soap-biblioteca-db-postgres
    ports:
      - "5433:5432"
    volumes:
      - soap-biblioteca-db-postgres-volume:/var/1ib/postgresql/data/
      
  soap-biblioteca-api: 
    container_name: soap-biblioteca-api-payara
    build: .
    image: soap-biblioteca-api-payara
    ports:
      - "8081:8080"
    links:
      - "soap-biblioteca-db:soap-biblioteca-db"

volumes:
  soap-biblioteca-db-postgres-volume:
    driver: local